language: python

python:
 - "2.7"

before_install:
 - sudo apt-get install gfortran libcfitsio3-dev python-matplotlib python-pyfits python-scipy
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - pip install coveralls

install: 
 - pip install -r requirements.txt 
 - python setup.py build_ext --inplace

script:
 - nosetests --with-coverage --cover-package=oracle

after_success:
 - coveralls

notifications:
 email:
  - andycasey@gmail.com
