language: python

python:
#  - "3.4"
  - "2.7"

before_install: 
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - ./miniconda.sh -b
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib
 - pip install coveralls

install: 
#  - pip install -r requirements.txt 
  - python setup.py build_ext --inplace

script:
  - nosetests --with-coverage --cover-package=oracle

after_success:
  - coveralls

notifications:
  email:
    - andycasey@gmail.com
