language: python

python:
 - "2.7"

virtualenv:
 system_site_packages: true

before_install:
 # Install PyGithub, which we will use to update the GitHub commit status
 # Need my version of PyGithub at the moment so that we can provide context to statuses
 - pip install https://github.com/andycasey/PyGithub/archive/master.zip
 # If applicable, set a pending status for the commit
 - python status.py
 
 # OK now install the stuff we need
 - sudo apt-get install gfortran libcfitsio3-dev python-matplotlib python-pyfits python-scipy
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - pip install coveralls

install:
 - pip install -r requirements.txt --use-mirrors
 - python setup.py build_ext --inplace --with-atmospheres

script:
 - nosetests --with-coverage --cover-package=oracle

after_success:
 - coveralls
 # If we are on a pull request, run the science verification tests.
 - "if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then python science.py > science.log; fi"

after_script:
 # Where applicable, update the commit status with a success, error, or failure
 - python status.py 

notifications:
 email:
  - andycasey@gmail.com
