sudo: true
language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  # Install required packages
  - sudo apt-get install gfortran libcfitsio3-dev python-matplotlib python-pyfits python-scipy
  # Setup a faux display for matplotlib
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: 
  - pip install coveralls
  - pip install -r requirements.txt --use-mirrors
  - python setup.py build_ext --inplace
script:
  - nosetests --with-coverage --cover-package=oracle
after_success:
  - coveralls
  # Science script
notifications:
  email:
    - andycasey@gmail.com
